"use client";

import Sidebar from "@/components/Dashboard/Sidebar";
import PDFViewer from "@/components/Dashboard/PDFViewer";
import Explanation from "@/components/Dashboard/Explanation";
import Quiz from "@/components/Dashboard/Quiz";
import { useState, useEffect } from "react";

// For now, hardcoded data - will be replaced with backend data later
// Main topic will come from PDF analysis in agent_backend
const mainTopic = "Trees";

// Subtopics are modular - simply add more objects to the array
// Each subtopic needs: { id: string, title: string }
// The id should be unique, title is what displays in the sidebar
const subtopics = [
  { id: "1", title: "Subtopic 1" },
  { id: "2", title: "Subtopic 2" },
  { id: "3", title: "Subtopic 3" },
  // To add more subtopics, simply add:
  // { id: "4", title: "Subtopic 4" },
];

// Sample data - will come from backend
const explanationText = "This is a sample explanation text that will be generated by the backend agent. It explains the concept shown in the PDF above.";
const questionText = "What is the time complexity of searching in a binary search tree?";
const answers = [
  { id: "a", text: "O(n)", isCorrect: false },
  { id: "b", text: "O(log n)", isCorrect: true },
  { id: "c", text: "O(1)", isCorrect: false },
  { id: "d", text: "O(n log n)", isCorrect: false },
];

export default function DashboardPage() {
  const [pdfFile, setPdfFile] = useState<File | string | null>(null);

  useEffect(() => {
    // Try to get PDF from sessionStorage or localStorage
    // For now, we'll use a placeholder
    // In the future, this will come from the backend
    const storedFile = sessionStorage.getItem("uploadedPDF");
    if (storedFile) {
      // If it's a blob URL, use it directly
      setPdfFile(storedFile);
    }
  }, []);

  return (
    <div className="h-screen bg-black flex overflow-hidden">
      {/* Sidebar */}
      <Sidebar mainTopic={mainTopic} subtopics={subtopics} />

      {/* Main Content - split into two halves */}
      <div className="flex-1 ml-64 flex gap-6 p-6">
        {/* Left half - PDF Viewer */}
        <div className="w-1/2 h-full">
          <PDFViewer file={pdfFile} />
        </div>

        {/* Right half - Explanation and Quiz stacked */}
        <div className="w-1/2 h-full flex flex-col gap-6">
          {/* Explanation Container - top half */}
          <div className="h-1/2">
            <Explanation text={explanationText} />
          </div>

          {/* Quiz Container - bottom half */}
          <div className="h-1/2">
            <Quiz question={questionText} answers={answers} />
          </div>
        </div>
      </div>
    </div>
  );
}
