"use client";

import Sidebar from "@/components/Dashboard/Sidebar";
import PDFViewer from "@/components/Dashboard/PDFViewer";
import Explanation from "@/components/Dashboard/Explanation";
import Quiz from "@/components/Dashboard/Quiz";
import { useState, useEffect } from "react";

// For now, hardcoded data - will be replaced with backend data later
// Main topic will come from PDF analysis in agent_backend
const mainTopic = "Trees";

// Subtopics are modular - simply add more objects to the array
// Each subtopic needs: { id: string, title: string }
// The id should be unique, title is what displays in the sidebar
const subtopics = [
  { id: "1", title: "Subtopic 1" },
  { id: "2", title: "Subtopic 2" },
  { id: "3", title: "Subtopic 3" },
  // To add more subtopics, simply add:
  // { id: "4", title: "Subtopic 4" },
];

// Sample data - will come from backend
const explanationText = "This is a sample explanation text that will be generated by the backend agent. It explains the concept shown in the PDF above.";
const questionText = "What is the time complexity of searching in a binary search tree?";
const answers = [
  { id: "a", text: "O(n)", isCorrect: false },
  { id: "b", text: "O(log n)", isCorrect: true },
  { id: "c", text: "O(1)", isCorrect: false },
  { id: "d", text: "O(n log n)", isCorrect: false },
];

export default function DashboardPage() {
  const [pdfFile, setPdfFile] = useState<File | string | null>(null);

  useEffect(() => {
    // Try to get PDF from sessionStorage or localStorage
    // For now, we'll use a placeholder
    // In the future, this will come from the backend
    const storedFile = sessionStorage.getItem("uploadedPDF");
    if (storedFile) {
      // If it's a blob URL, use it directly
      setPdfFile(storedFile);
    }
  }, []);

  return (
    <div className="min-h-screen bg-gray-50 flex">
      {/* Sidebar */}
      <Sidebar mainTopic={mainTopic} subtopics={subtopics} />

      {/* Main Content */}
      <div className="flex-1 ml-64 p-6">
        <div className="max-w-7xl mx-auto space-y-6">
          {/* PDF Viewer - Full height container */}
          <div className="h-[600px]">
            <PDFViewer file={pdfFile} />
          </div>

          {/* Explanation Container - 0.5 height of PDF */}
          <div className="h-[300px]">
            <Explanation text={explanationText} />
          </div>

          {/* Quiz Container - 0.5 height of PDF */}
          <div className="h-[300px]">
            <Quiz question={questionText} answers={answers} />
          </div>
        </div>
      </div>
    </div>
  );
}
